// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx5HAlrIIgqTEuuGVnbixHuGXOFCpdGFw',
    appId: '1:1007210607013:android:c0607944f381c430f1384c',
    messagingSenderId: '1007210607013',
    projectId: 'imob-expert',
    storageBucket: 'imob-expert.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwEMk7phmDXc4CRxKTW5Ks-HcSGQAgmz4',
    appId: '1:1007210607013:ios:a23a5333069df0a1f1384c',
    messagingSenderId: '1007210607013',
    projectId: 'imob-expert',
    storageBucket: 'imob-expert.appspot.com',
    iosBundleId: 'com.example.imobExpert',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDffbNXjjC48uCczl87Qb4cLkcEmFBpY7w',
    appId: '1:1007210607013:web:79f671c730ede2b8f1384c',
    messagingSenderId: '1007210607013',
    projectId: 'imob-expert',
    authDomain: 'imob-expert.firebaseapp.com',
    storageBucket: 'imob-expert.appspot.com',
    measurementId: 'G-CZ1CQV95KD',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwEMk7phmDXc4CRxKTW5Ks-HcSGQAgmz4',
    appId: '1:1007210607013:ios:a23a5333069df0a1f1384c',
    messagingSenderId: '1007210607013',
    projectId: 'imob-expert',
    storageBucket: 'imob-expert.appspot.com',
    iosBundleId: 'com.example.imobExpert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDffbNXjjC48uCczl87Qb4cLkcEmFBpY7w',
    appId: '1:1007210607013:web:04f688ae8403ee32f1384c',
    messagingSenderId: '1007210607013',
    projectId: 'imob-expert',
    authDomain: 'imob-expert.firebaseapp.com',
    storageBucket: 'imob-expert.appspot.com',
    measurementId: 'G-TLHX3Q95GN',
  );
}
